### ISSUE TITLE
Detach XSLT from specific paths

### ISSUE THREAD

**Issue by ppiegaze** [Adobe-Marketing-Cloud/aem-content-importer#10]
The XSLT code needs to be detached from specific paths that are currently hardcoded. Specifically the target path of the converteted pages and the sling:resourceType path for the created pages

**Comment by galapagoss** [comment]
I didnt' understand very well the issue.
The target path of the converted pages is stored in the config_params.xml (target) and the sling:resourceType path is an implicit match set into XLS declaration (configurable but by default in /apps/aem-importer/resources/*).
Unless you mean to declare parameters in the XLS code and pass the values through Java code

**Comment by ppiegaze** [comment]
Yes, I mean that the parameters must be passed into the XSLT from the Java code.

Maybe the best way to do this is probably not to pass individual parameters, but to just pass the location of the config file, which the XSLT can then read.

Does this make sense?

**Comment by galapagoss** [comment]
Yes, sure. 
I think I can pass the entire properties file using this method http://docs.oracle.com/javase/7/docs/api/javax/xml/transform/Transformer.html#setOutputProperties(java.util.Properties) then you will be able to handle all cases.
Let me know if you agree

**Comment by ppiegaze** [comment]
I think the correct method is this:

http://docs.oracle.com/javase/7/docs/api/javax/xml/transform/Transformer.html#setParameter(java.lang.String, java.lang.Object)

**Comment by galapagoss** [comment]
Ok, in this case I'm already implementing it for the issue #12

**Comment by ppiegaze** [comment]
Yes. This issue (#10) is really just for me. It is meant to refer to the changes required in the XSLT code, as opposed to the changes required in Java (which is #12).

**Comment by galapagoss** [comment]
Ah ok, sorry I didn't see the assignment :)
Ok it's clear
