### ISSUE TITLE
graphics folder location must be parameterized

### ISSUE THREAD

**Issue by ppiegaze** [Adobe-Marketing-Cloud/aem-content-importer#11]
In addition to the existing parameters the location of the graphics folder within the source dita folder should be parameterized as well.

**Comment by galapagoss** [comment]
In the config_params.xml there is the property "graphicFolders" which defines the folder where to search graphic resources.
Let me know if it's enough or you're referreing to something different

**Comment by ppiegaze** [comment]
Yes. You are right, this is already done. Thanks.
