### ISSUE TITLE
Use OSGi to lookup Transformers

### ISSUE THREAD

**Issue by ppiegaze** [Adobe-Marketing-Cloud/aem-content-importer#26]
The lookup of available transformers should be done through the OSGi mechanism, not manually.

**Comment by galapagoss** [comment]
Implemented the OSGI mechanism into XMLTransformerHelper.
Moreover I created a new test bundle which implements a "No Action" version.
Since now all transformers are services we can face issues of concurrential execution, as long as I make the service stateless #27
