### ISSUE TITLE
Stateless service

### ISSUE THREAD

**Issue by ppiegaze** [Adobe-Marketing-Cloud/aem-content-importer#27]
The upload and transform service should be made stateless as per Alex's comments during the phone meeting of 18 Dec 2014.

**Comment by galapagoss** [comment]
Changed the Interface using only one method "transformer" keeping the service stateless.
Since the saxon transformer needs a URIResolver instance I declared a specific class nested inside.
It would be interesting make a massive test with the command line tool for checking out concurrent processes
