### ISSUE TITLE
Implement logic in java classes not in JSPs

### ISSUE THREAD

**Issue by ppiegaze** [Adobe-Marketing-Cloud/aem-content-importer#29]
IN general we want to avoid JSPs as this is supposed to be best practices code. This means that all interface should be Sightly and all servlet code should be straight Java. In our case we have determined that there will be les UI than originally envisioned. Instead we will just have a single simple upload component. This component's presentation logic should be in Sightly. All supporting code including the POST servlet should be pure Java, not JSP.

**Comment by jralonso84** [comment]
I've started moving JSP into Sightly manner. I would like to ask you about some styles and javascript are embedded in the component. Should I create a clientlib with those or leave as it's right now? After that, I have to migrate POST jsp to a sling servlet to finish this issue or I misunderstood something?

**Comment by ppiegaze** [comment]
Yes, Javascript and css must be put in clientlibs and the POST jsp should be converted to a sling servlet. You have exactly the right idea.

**Comment by jralonso84** [comment]
Finished them
