### ISSUE TITLE
Update saxon to latest version

### ISSUE THREAD

**Issue by ppiegaze** [Adobe-Marketing-Cloud/aem-content-importer#34]
The version of Saxon used by the build should be updated to the following:
```
<dependency>
    <groupId>net.sf.saxon</groupId>
    <artifactId>Saxon-HE</artifactId>
    <version>9.6.0-3</version>
</dependency>
```
See: http://search.maven.org/#artifactdetails%7Cnet.sf.saxon%7CSaxon-HE%7C9.6.0-3%7Cjar

**Comment by ppiegaze** [comment]
Was there a reason to use the older version?

**Comment by galapagoss** [comment]
Yes, you're right, it was an old misprint which embedded the jar. fix it

**Comment by galapagoss** [comment]
The previous version was an osgi bundle whereas what you suggest it's a library, so I embedded it into the importer bundle as a private package

**Comment by ppiegaze** [comment]
Yes, embedding the lib into the bundle is fine.
