### ISSUE TITLE
XMLTransformerDocbookImpl + XSLT

### ISSUE THREAD

**Issue by ppiegaze** [Adobe-Marketing-Cloud/aem-content-importer#36]
A new Impl of the transformer needs to be created that processes Docbook source. The Java part will be almost identical to the DITA impl, but the XSLT will be different.

**Comment by ppiegaze** [comment]
Add a new class, `XMLTransformerDocbookImpl`. Initially it can be identical to `XMLTransformerDITA Impl` with two excpetions:

- Its name (obviously)
- The XSLT file that it uses: `XMLTransformerDocbookImpl` should use a different XSLT file, called `docbook-to-content.xsl`

This new file, `docbook-to-content.xsl` will initially be identical to `dita-to-content.xsl` (except for name).

We just want to demonstrate the option to choose between different transformers, even though initially they will actually do exactly the same thing. Later we will change the impls to actually convert from docbook.

**Comment by acollign** [comment]
There is probably a lot a code that can be shared so I would recommend to write an abstract class to ensure we don't duplicate code.

**Comment by galapagoss** [comment]
it was mine!! :)

**Comment by galapagoss** [comment]
I enclosed the import procedure in the abstract class as well. 
Moreover I saw that transformer initialization has been moved on the abstract class, check out to not encounter on classloader troubles
Previously I prepared an alternative bundle 'aem-content-importer-bundle-2' just for testing OSGI service registration, in fact I have created a second transform called 'NoActionTransformer' which do nothing, I think it can be removed

**Comment by ppiegaze** [comment]
Yep, the extra bundle should be removed.

**Comment by jralonso84** [comment]
Extra bundle has been deleted.
