### ISSUE TITLE
Use same XSLT for unit tests as for install

### ISSUE THREAD

**Issue by ppiegaze** [Adobe-Marketing-Cloud/aem-content-importer#38]
There seem to be two copies of `dita-to-content.xsl`. One that is used by the implementation and another used by the unit tests:

- `aem-content-importer/aem-content-importer-content/src/main/content/jcr_root/apps/aem-importer/resources/dita-to-content.xsl`

- `aem-content-importer/aem-content-importer-bundle/src/test/resources/dita-to-content.xsl`

This makes no sense. We want to test the same file as we install. There should only be one XSLT file, the first one, above.

**Comment by jralonso84** [comment]
We are using a xsl file ( the same as the installation) in a unit test because we only are checking transformer process without some integration with AEM. Do you agree with that? Or else, do you prefer to change as integration test?

**Comment by ppiegaze** [comment]
Can't the unit test just use this file

`aem-content-importer/aem-content-importer-content/src/main/content/jcr_root/apps/aem-importer/resources/dita-to-content.xsl`

instead of this file

`aem-content-importer/aem-content-importer-bundle/src/test/resources/dita-to-content.xsl` ?

I know that for the unit test it does not really matter what the content of the xsl file is, but still it would be nice to just iuse the same one for everything. Does this make sense?

**Comment by jralonso84** [comment]
Unit test changed to take dita-to-content.xsl from the path installation.
