### ISSUE TITLE
make example.zip in tools same as exampleTest.zip

### ISSUE THREAD

**Issue by ppiegaze** [Adobe-Marketing-Cloud/aem-content-importer#40]
The two example zip files should probably be the same or the one in tools should be removed

**Comment by jralonso84** [comment]
Done it

**Comment by ppiegaze** [comment]
We should remove `aem-content-importer/tools-files/example.zip`.

And, this file, `aem-content-importer/aem-content-importer-bundle/src/test/resources/exampleTest.zip`, should not be checked-in as a zip. The zip should be built during the maven install from a directory of the example files. This allows us to control the contents of the zip within the git system.

**Comment by jralonso84** [comment]
I'm thinking about giving up a maven task to create a zip file from a folder. Instead of this, integration test could manage it directly using a example folder in src/test/resources. What do you think?

**Comment by ppiegaze** [comment]
This is file for testing the import functionality. Later when we have Jenkins continuous integration we might want to test the upload and unzipping of a zip file, but that would be a different issue.

**Comment by jralonso84** [comment]
I enclosed in the integration test the task to prepare a zip file from a folder for testing different things. So, right now we have a folder with all necessary files for zipping and doing the import functionality.
